# 🛡️ Azure Sentinel SIEM & Live Honeypot Cyber Attack Map

![Azure](https://img.shields.io/badge/Microsoft%20Azure-0089D6?style=for-the-badge&logo=microsoft-azure&logoColor=white)
![Microsoft Sentinel](https://img.shields.io/badge/Microsoft%20Sentinel-0078D4?style=for-the-badge&logo=microsoft&logoColor=white)
![PowerShell](https://img.shields.io/badge/PowerShell-5391FE?style=for-the-badge&logo=powershell&logoColor=white)
![KQL](https://img.shields.io/badge/Kusto%20Query%20Language-0052CC?style=for-the-badge&logo=azure-data-explorer&logoColor=white)

## 🎯 Objective
The **Azure Sentinel SIEM and Virtual Machine Honeypot** project is an interactive cloud security lab designed to simulate a vulnerable environment. By intentionally configuring a Windows Virtual Machine to be fully exposed to the internet (**Honeypot**), this project captures real-world RDP brute-force attacks from global threat actors.

A custom PowerShell script was developed to extract attacker IP addresses from **Windows Event Logs (Event ID 4625)**, query a third-party geolocation API, and forward this enriched telemetry to an **Azure Log Analytics Workspace**. Finally, **Microsoft Sentinel (SIEM)** was utilized to parse the data using **Kusto Query Language (KQL)** and map the global attack sources on a live dashboard.

---

## 🛠️ Skills & Technologies Learned
* **Cloud Security Configuration:** Deploying Azure resources, Virtual Networks, and manipulating **Network Security Groups (NSGs)** to create intentional vulnerabilities.
* **Log Management & SIEM:** Setting up Azure Log Analytics Workspace and configuring **Microsoft Sentinel** data connectors.
* **Scripting & Automation:** Writing a custom [PowerShell Script](honeypot_script.ps1) to parse XML event logs and automate REST API calls for Threat Intelligence enrichment.
* **Data Parsing (KQL):** Utilizing **Kusto Query Language** to extract and manipulate custom log data into structured columns.
* **Threat Intelligence:** Analyzing Windows Security Event ID `4625` (Failed Logon) to extract actionable Indicators of Compromise (IOCs).

---

## 📸 Step-by-Step Implementation & Evidence

### 1. Intentional Vulnerability (Honeypot Configuration)
To attract background internet noise and threat actors, a Windows Virtual Machine was deployed. The **Network Security Group (NSG)** inbound rule was intentionally configured to allow traffic from **Any source (`*`) on Port `3389` (RDP)**.

![Azure NSG Rule](azure-nsg-rule.png)

### 2. Capturing the Intrusions (Windows Event Viewer)
Shortly after exposure, automated bots and attackers began brute-forcing the RDP service. These attempts were successfully recorded in the Windows Security logs as **Event ID 4625 (Audit Failure)**.

![Windows Event Viewer 4625](event-viewer-4625.png)

### 3. Telemetry Extraction & Enrichment (PowerShell Scripting)
I developed a custom PowerShell script ([`honeypot_script.ps1`](honeypot_script.ps1)) to continuously monitor Event ID 4625. It extracts the attacker's IP address, queries the `ipgeolocation.io` REST API, and outputs structured live geolocation data (Latitude, Longitude, Country, etc.).

![PowerShell Live Output](powershell-live-output.png)

### 4. Log Analytics & Data Parsing (KQL)
The custom logs generated by the script were ingested into an Azure Log Analytics Workspace. I utilized **Kusto Query Language (KQL)** to parse the raw text data into distinct structured columns (`latitude`, `longitude`, `sourcehost`, `country`), making it ready for SIEM visualization.

![KQL Query Logs](kql-query-logs.png)

### 5. Threat Visualization (Azure Sentinel Live Map)
Finally, a custom workbook was built in **Microsoft Sentinel**. The parsed geolocation coordinates were plotted on an interactive global map, providing a live visual representation of where malicious RDP attacks were originating globally.

![Azure Sentinel Map](sentinel-map.png)

---

## 💡 Conclusion
This lab provided practical, hands-on experience in building a **SOC (Security Operations Center)** environment from the ground up. By analyzing live threat actor behavior and brute-force methodologies, I gained a deeper understanding of how quickly cloud resources are targeted when exposed, and how SIEM solutions ingest, parse, and visualize threat intelligence to defend infrastructure.
